### ISSUE TITLE
kaby lake

### ISSUE THREAD

**Issue by coolfire168** [pocka/docker-ffmpeg-qsv#1]
I  test it on kaby lake. It's not work.
Any update?please....

**Comment by pocka** [comment]
Sorry, this is an exprimental and no longer maintained repo (I've forgot deleting).
The image does not work for my machine(skylake + H170M) too.

If you are looking for HW en/decodable ffmpeg image, try [pocka/docker-ffmpeg-vaapi](https://github.com/pocka/docker-ffmpeg-vaapi).
It works on my skylake machine.

**Comment by coolfire168** [comment]
But it can work for my machine (i5 skylake ).
So i think you can do it for kabylake. I need QSV.......please....

**Comment by pocka** [comment]
> But it can work for my machine (i5 skylake ).
Wow, I'll try again later!

> So i think you can do it for kabylake.
OK, before tackling the issue, can you show me:
1) command and output where the operation failed
2) Linux distribution and docker version
3) output of `lspci -v -s 00:02.0`(detail of Intel HD Graphics)

**Comment by coolfire168** [comment]
1. I'm not sure Intel SDK support kabylake? I just use your docker-ffmpeg-qsv to transcode then it is fail.
   docker run -v /data:/data pocka/ffmpeg-qsv -i /data/1.h264 -c:v h264_qsv -look_ahead 0 -q 20 /data/1.mp4
After command.It show 
> 
ffmpeg version 3.2.2 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-11)
  configuration: --enable-nonfree --enable-small --enable-gpl --enable-libmfx --disable-doc --disable-debug
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, h264, from '/data/1.h264':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264, yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 1200k tbn, 59.94 tbc
> 
The 1.mp4 file size is zero.......
Then I command
>
docker run  -v /data:/data  --entrypoint="/bin/bash" -it --name ffmpeg-qsv pocka/ffmpeg-qsv
ffmpeg -i /data/1.h264 -c:v h264_qsv -look_ahead 0 -q 20 /data/1.mp4
>
Show error message
 >
Illegal instruction (core dumped)
>
2. Centos 7.2.1511 and   Docker version 1.12.5, build 047e51b/1.12.5

3.command lspci -v -s 00:02.0
>
00:02.0 VGA compatible controller: Intel Corporation Device 5902 (rev 04) (prog-if 00 [VGA controller])
	Subsystem: Intel Corporation Device 2112
	Flags: bus master, fast devsel, latency 0, IRQ 11
	Memory at 2ffe000000 (64-bit, non-prefetchable) [size=16M]
	Memory at c0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at f000 [size=64]
	Expansion ROM at <unassigned> [disabled]
	Capabilities: [40] Vendor Specific Information: Len=0c <?>
	Capabilities: [70] Express Root Complex Integrated Endpoint, MSI 00
	Capabilities: [ac] MSI: Enable- Count=1/1 Maskable- 64bit-
	Capabilities: [d0] Power Management version 2
	Capabilities: [100] #1b
	Capabilities: [200] Address Translation Service (ATS)
	Capabilities: [300] #13
>
But i want to use kabylake GPU to transcode not use graphics card.

**Comment by pocka** [comment]
Intel Media Server Studio doesn't support 7th gen core...

[https://software.intel.com/en-us/intel-media-server-studio/details](https://software.intel.com/en-us/intel-media-server-studio/details)

**Comment by coolfire168** [comment]
Well......thanks a lot...>_<
